import s from "./page.module.css";

const Home = () => {
  return (
    <div className={s.background}>
      <div className={s.header}>
        <p className={s.title}>Privacy Policy for React Native Calculator</p>
      </div>
      <div className={s.contentWrapper}>
        <div className={s.content}>
          <h1 className={s.h1}>Privacy Policy</h1>
          <p>Last updated: October 26, 2024</p>
          <p>This Privacy Policy describes Our policies and procedures when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          <p>We do not collect or use any Personal Data by using the Service or even installing the Application. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className={s.anchor}>Privacy Policy Generator</a>.</p>
          <h2 className={s.h2}>Interpretation and Definitions</h2>
          <h3 className={s.h3}>Interpretation</h3>
          <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          <h3 className={s.h3}>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li>
              <p><strong>Application</strong> refers to React Native Calculator, the software program provided by the Company.</p>
            </li>
            <li>
              <p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Juan Pablo Azambuyo.</p>
            </li>
            <li>
              <p><strong>Country</strong> refers to:  Argentina</p>
            </li>
            <li>
              <p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
            </li>
            <li>
              <p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
            </li>
            <li>
              <p><strong>Service</strong> refers to the Application.</p>
            </li>
            <li>
              <p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
            </li>
            <li>
              <p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
            </li>
          </ul>
          <h2 className={s.h2}>Links to Other Websites</h2>
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          <h2 className={s.h2}>Changes to this Privacy Policy</h2>
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          <p>We will let You know via a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          <h2 className={s.h2}>Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul>
            <li>
              <p>By email: <a href="mailto:juanpabloazambuyo@gmail.com" className={s.anchor}>juanpabloazambuyo@gmail.com</a></p>
            </li>
            <li>
              <p>By visiting this page on our website: <a href="https://pabloaza89.github.io/portfolio" rel="external nofollow noopener" target="_blank" className={s.anchorBottom}>https://pabloaza89.github.io/portfolio</a></p>
            </li>
          </ul>
        </div>
      </div>
      <div className={s.footer}>
        <p>Generated using <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" className={s.anchor}>TermsFeed Privacy Policy Generator</a></p>
      </div>
    </div>
  );
}

export default Home;