name: Auto Deploy
on:
  push:
    branches: [ "main" ]
env:
  CI: false
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Copy README from origin root to GH-Pages public folder
      run: cp "./README.md" "./public/README.md"
    - run: npm ci
    - run: npm run build --if-present
    - run: git config --global user.email "juanpabloazambuyo@gmail.com"
    - run: git config --global user.name "Juan Pablo Azambuyo"
    - run: git remote set-url origin https://${{ secrets.USER_GITHUB_TOKEN }}@github.com/PabloAza89/portfolio.git
    - run: npm run deploy --if-present